name = "TestJETLS"
uuid = "66d4ff65-fdce-4266-a827-6ec76ccab5a7"
version = "0.1.0"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]

[sources]
JETLS = {url = "https://github.com/aviatesk/JETLS.jl", rev = "master"}

[compat]
julia = "1.12.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"
JETLS = "a3b70258-0602-4ee2-b5a6-54c2470400db"

[targets]
test = ["Test", "Jive", "JETLS"]
